from .animal import Animal
from .alpaca import Alpaca
from .goat import Goat
from .llama import Llama
from .pig import Pig
from .pony import Pony
from .duck import Duck
from .koi import Koi
from .polarbear import Polarbear
from .seal import Seal
from .turtle import Turtle
from .copperhead import Copperhead
from .cottonmouth import Cottonmouth
from .hellbender import Hellbender
from .hognose import Hognose
from .timberrattlesnake import Timberrattlesnake
